hevy_mysql:
  target: dev
  outputs:
    dev:
      type: mysql
      server: localhost
      port: 3306
      schema: SILVER
      username: "{{ env_var('DBT_USER') }}"
      password: "{{ env_var('DBT_PASSWORD') }}"